# Site Info
title: 'CodingBear의 개발 블로그'
tagline: 'CodingBear의 개발 블로그'
description: '모든 코드를 먹어치우는 곰입니다'
baseurl: ""
url: 'https://HaeUlNam.github.io'
logo: ''

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: 'NAM HAEUL'
  description: 'CodingBear(NAM HAEUL)'
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/HaeUlNam
    #facebook:  https://www.facebook.com/wayhome25
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:    mailto:harrynam3@naver.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/blog/categories/#til' }
    - { TIE (Today I Exited): '/blog/categories/#tie' }
    - { 자료구조 알고리즘 구현: '/blog/categories/#자료구조-알고리즘-구현'}
    - { PS(Problem-Solve): '/blog/categories/#PS(Problem-Solve)'}
    - { ML (Machine Learning): '/blog/categories/#ml' }
    - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-133169356-1' # leave blank if you don't want google analytics
disqus_short_name: 'HaeUlNam-github-io' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
